CREATE TABLE polyclinic (
    clinic_id VARCHAR(10) PRIMARY KEY,
    clinic_name VARCHAR(50) NOT NULL,
    location VARCHAR(50),
    is_deleted TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);