CREATE TABLE patient (
    medical_record_no VARCHAR(50) PRIMARY KEY,
    patient_name VARCHAR(255) NULL,
    gender VARCHAR(50) NULL,
    place_of_birth VARCHAR(255) NULL,
    date_of_birth DATE NULL,
    address TEXT NULL,
    phone_number VARCHAR(20) NULL,
    identity_type VARCHAR(20) NULL,
    identity_number VARCHAR(50) NULL,
    city VARCHAR(255) NULL,
    postal_code VARCHAR(10) NULL,
    medical_record_date DATE NULL,
    birth_weight DECIMAL(5,2) NULL,
    ethnicity VARCHAR(255) NULL,
    subdistrict VARCHAR(255) NULL,
    district VARCHAR(255) NULL,
    regency VARCHAR(255) NULL,
    province VARCHAR(255) NULL,
    citizenship VARCHAR(20) NULL,
    country VARCHAR(255) NULL,
    language VARCHAR(255) NULL,
    blood_type VARCHAR(5) NULL,
    KK_number VARCHAR(50) NULL,
    marital_status VARCHAR(20) NULL,
    religion VARCHAR(20) NULL,
    occupation VARCHAR(50) NULL,
    education VARCHAR(50) NULL,
    npwp VARCHAR(50) NULL,
    file_location VARCHAR(255) NULL,
    
    relative_name VARCHAR(255) NULL,
    relative_relationship VARCHAR(50) NULL,
    relative_phone VARCHAR(20) NULL,
    relative_identity_number VARCHAR(20) NULL,
    relative_occupation VARCHAR(255) NULL,
    relative_address TEXT NULL,
    relative_city VARCHAR(255) NULL,
    relative_postal_code VARCHAR(10) NULL,
    
    mother_medical_record_no VARCHAR(50) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) DEFAULT 0,
    FOREIGN KEY (mother_medical_record_no) REFERENCES patient(medical_record_no)
);