### Variables
@baseUrl = http://localhost:8080/api/v1

### Get ALl
GET {{baseUrl}}/transactions
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzI1NjIsInVzZXJfaWQiOjF9.G0iBP68wN_oFPqoUttQbAGw9GWKkRpbtuE2OMeYrJoE;
Content-Type: application/json

### Get By Transaction ID
GET {{baseUrl}}/transactions/1
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzI1NjIsInVzZXJfaWQiOjF9.G0iBP68wN_oFPqoUttQbAGw9GWKkRpbtuE2OMeYrJoE;
Content-Type: application/json

### Delete By Medical Record No
DELETE {{baseUrl}}/patients/20250126193707002/transactions
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzI1NjIsInVzZXJfaWQiOjF9.G0iBP68wN_oFPqoUttQbAGw9GWKkRpbtuE2OMeYrJoE;
Content-Type: application/json

### Update
PUT {{baseUrl}}/transactions/POL03
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgxNzI1NjIsInVzZXJfaWQiOjF9.G0iBP68wN_oFPqoUttQbAGw9GWKkRpbtuE2OMeYrJoE;
Content-Type: application/json

{
    "registration_fee": 50000,
    "examination_fee": 150000,
    "total_fee": 200000,
    "discount": 5000,
    "total_payment": 195000,
    "payment_type": "Cash",
    "payment_status": "Lunas"
}